services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mohamedomar
      MYSQL_DATABASE: school_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - micro-net

  config-server:
    build: ./config-server
    platform: linux/arm64
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_APPLICATION_NAME=config-server
      - SERVER_PORT=8888
    networks:
      - micro-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  discovery:
    build: ./discovery
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=discovery-service
      - SERVER_PORT=8761
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    networks:
      - micro-net
    depends_on:
      - config-server
      - mysql

  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8222:8222"
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - SERVER_PORT=8222
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - micro-net
    depends_on:
      - discovery

  school:
    build: ./school
    container_name: school-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_APPLICATION_NAME=school-service
      - SERVER_PORT=8090
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/school_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mohamedomar
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - micro-net
    depends_on:
      - discovery
      - mysql

  student:
    build: ./student
    container_name: student-service
    ports:
      - "8091:8091"
    environment:
      - SPRING_APPLICATION_NAME=student-service
      - SERVER_PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/school_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mohamedomar
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - micro-net
    depends_on:
      mysql:
        condition: service_healthy
      discovery:
        condition: service_started

volumes:
  mysql_data:

networks:
  micro-net:
    driver: bridge