spring:
  application:
    name: university
datasource:
  url: jdbc:mysql://localhost:3306/microservice-university?createDatabaseIfNotExist=true
  username: root
  password: mohamedomar
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
server:
  port: 8092
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

# Configuration pour les clients Feign
application:
  config:
    school-url: http://localhost:8090/schools